---
MAIL:
  LOGIN: "xxxxxxxxxxxxxxx@gmail.com"
  PASSWD: "XXXXXXXXXXXXXXXXX"
  SERVER: "imap.gmail.com"

EVERNOTE:
  CONSUMER_KEY: "XXXXXXXXXXXX"
  CONSUMER_SECRET: "XXXXXXXXXXXXXXXXXXXXX"
  ACCESS_TOKEN: "S=XX:U=XXXX:XXXXXXXXXXXXXXXXXXXXXXXXXXXXX"

SLACK:
  TEAM: "XXXXXXX"
  TOKEN: "xoxp-XXXXXXXXXX-XXXXXXXXXX-XXXXXXXXXX-XXXXXX"
  CHANNEL: "#general"
  USERNAME: "XXXXXXXXXXXXXXXXXXXXXXX"
  COUNT: 20

TOGGL:
  TOKEN: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"

# if you wants to ignore the hidden directory(.) when search, IGNORE_HIDDEN:true
# default false
DOCUMENT:
  PATH: "XXXXXXXXXXXXXXXXXXX"
  IGNORE: "XXXXXX,XXXXXX"
  IGNORE_HIDDEN: XXXX